[package]
name = "bundler"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1"
flate2 = "1"
serde = { version = "1", features = ["derive"] }
tar = "0.4"
toml = { version = "0.7.3", default-features = false, features = ["parse"] }
